Fix android modal width
mmazzarolo/react-native-dialog pull request #152
Opened 2022-12-23 08:09 UTC by litinskii

For iOS platform we have fixed width 
<img width="386" alt="image" src="https://user-images.githubusercontent.com/10028441/209297185-ac0356cd-94ef-4565-bfc5-4562c481f9b8.png">
in this case when we have dynamic content like input and user type something  modal container not increase witdh, so we need to do the same for other platform.

Before
https://user-images.githubusercontent.com/10028441/209297979-cc201a21-63e5-4237-ba0d-4a9f7899f094.mov

After
https://user-images.githubusercontent.com/10028441/209298011-543a4ed1-f20e-49b2-805a-e84fa27a20da.mov

# Overview

# Test Plan

2022-12-23 08:09 UTC, litinskii commented
@mmazzarolo ^

2022-12-24 09:53 UTC, mmazzarolo requested changes
Hola! Thanks for reporting and creating a PR. Wondering it we want a fixed-witdth value or something that scales a bit with the device size? Do you know what the iOS/Android guidelines say about this?

2022-12-24 15:28 UTC, litinskii commented
The problem is that now in this lib, you have different behavior for ios/android styles for container, if you check code you will see that for ios you have `width` style, for android you have `minWidth`.

<img width="204" alt="image" src="https://user-images.githubusercontent.com/10028441/209442576-bdd8b697-a692-43b2-a3de-3b9b3f61810b.png">


<img width="143" alt="image" src="https://user-images.githubusercontent.com/10028441/209442587-37f3f0c9-31fe-45d6-af57-045a6ce4597f.png">


I believe behavior should be the same, need to use  minWidth or width, but the same in ios/android.

2022-12-24 15:33 UTC, litinskii commented
btw if you check dialog in material https://m2.material.io/components/dialogs#usage dialog not maked wider if child content increasing, which is impossible if you use `minWidth ` and overflow hidden, and there are no point to use overflow hidden if you not use fixed width

2023-06-06 07:25 UTC, litinskii commented
@mmazzarolo do you have take a look ?

2025-05-22 13:23 UTC, closed without merging