refactor to React v16+
mmazzarolo/react-native-dialog pull request #73
Opened 2020-09-17 15:39 UTC by tyxou

the Readme.md should be ignored from commit

2020-09-19 08:29 UTC, mmazzarolo commented on src/Container.js
> +        animationType={(props.animationType)?props.animationType:"fade"}
🤔

2020-09-19 08:30 UTC, mmazzarolo requested changes
I'm experiencing a few issues running this version directly on iOS14 so I can't merge it as it is. I'll play around with it and update it where needed. Thanks!

2020-09-19 23:28 UTC, tyxou commented
Haven't tested it with iOS 14, sorry about that.

2020-10-11 09:20 UTC, mmazzarolo commented
@tyxou I integrated most of your changes in the new release: https://github.com/mmazzarolo/react-native-dialog/releases/tag/v6.0.0
Sorry if I haven't used your own branch but as you can see I also had a chance to work on other stuff in the same release :)
Thanks so much for your work!

2020-10-11 09:20 UTC, closed without merging